### ISSUE TITLE
Hotbar rendering variations

### ISSUE THREAD

**Issue by Coswics** [simply-kel/KelUI#1]
Toggle to render hearts, armor, and hunger above the "Redesigned Hotbar" UI.
Having things be small and vertical is a bit weird, so having them be above there would be good (possibly horizontal instead of vertical?)

**Comment by Coswics** [comment]
Being able to move the actionbar would be nice as well, since some servers use it for resource packs

**Comment by simply-kel** [comment]
First, I'll probably do a different version of the stats renderer.
Second, I've put off moving the hotbar to the center or left for now.
Third, I won't be porting my mods to 1.20.1 because of the many GUI changes from 1.20.1 to 1.20.2-4.

**Comment by simply-kel** [comment]
Hi, I made in [1.0.0-alpha.2](https://modrinth.com/mod/kelui/version/1.0.0-alpha.2) centering the hotbar and selecting the player's stat output
![image](https://github.com/simply-kel/KelUI/assets/86980879/a1ce3174-1dc3-45cf-aaaa-3ef536638894)
